[debug] [2024-04-09T00:20:11.693Z] ----------------------------------------------------------------------
[debug] [2024-04-09T00:20:11.696Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Shino\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2024-04-09T00:20:11.696Z] CLI Version:   13.7.1
[debug] [2024-04-09T00:20:11.696Z] Platform:      win32
[debug] [2024-04-09T00:20:11.696Z] Node Version:  v21.1.0
[debug] [2024-04-09T00:20:11.696Z] Time:          Mon Apr 08 2024 17:20:11 GMT-0700 (hora estándar del Pacífico de México)
[debug] [2024-04-09T00:20:11.696Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-04-09T00:20:11.699Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
[debug] [2024-04-09T00:20:12.052Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2024-04-09T00:20:12.052Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=117033589&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2024-04-09T00:20:19.557Z] Unable to open URL: Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:761:9)
    at module.exports (C:\Users\Shino\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\open\index.js:114:34)
    at open (C:\Users\Shino\AppData\Roaming\npm\node_modules\firebase-tools\lib\auth.js:137:5)
    at Server.<anonymous> (C:\Users\Shino\AppData\Roaming\npm\node_modules\firebase-tools\lib\auth.js:369:13)
    at Object.onceWrapper (node:events:629:28)
    at Server.emit (node:events:527:35)
    at Server.emit (node:domain:488:12)
    at emitListeningNT (node:net:1906:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
